-- Use SQL insert statements to add any
-- starting/dummy data to your database tables

-- EXAMPLE:

--  insert into "todos"
--    ("task", "isCompleted")
--    values
--      ('Learn to code', false),
--      ('Build projects', false),
--      ('Get a job', false);

SET standard_conforming_strings = off;


insert into "customers"
  ("username", "hashedPassword")
  values
      ('test', 'testPass');

insert into "items"
  ("name", "imageUrl",  "category", "description", "lowestPrice" )
  values
  ('CUBAN LINK BRACELET',  '/images/cuban-bracelet.webp',   'Bracelet',  'High shine for a high roller. The Cuban Link Bracelet is pure stainless steel with our iconic HJ stamped right in.\nDesigned to help show off your style, and features our innovative lobster clasp that lets you spend less time putting on your accessories and more time dripped out.\n7" is recommended for a clean fitted look whereas 8" is suggested for heavier wrists or a looser fit.', '$32.95'),

('ASTROLOGY RING', '/images/astrology-ring.webp',  'Ring', 'Listen to the messages from the moon. Gaze upon the stars for answers. And always pay attention to the eyes - they never lie.\nHere’s your chance to showcase the true nature of your personality - that’s what astrology’s all about. As one of our most iconic pieces, the Astrology Ring guides you along the path of deeper meaning.\nFeatured in the 4/20 4 Year Anniversary Collection' , '$36.95'),

('10MM HEAVY CUBAN CHAIN', '/images/10-mm-heavy-cuban-chain.webp', 'Chain', 'It’s time to finally go hard. The 10mm Heavy Cuban Chain is here for you to make a statement and create your own look.\nMade of pure solid stainless steel, this chain is designed to have the perfect weight and shine that’ll give you that luxury look you’ve been searching for. It’s purpose-built for those who want to make sure their drip stops going unnoticed.', '$36.95'),
('BUTTERFLY PENDANT', '/images/butterfly-pendant.webp', 'Pendant', 'Spread your wings with our Butterfly Pendant. Embrace the spiritual flow you’ve created between your mind and soul, showing how far you’ve come against the odds. Every day is its own battle, but it’s never a bad idea to take a second to recognize the progress you’ve made.\nSave on your order when you add an HJ chain. Couple this pendant with your choice between six 20” .925 sterling silver chains, ensuring you get the best match for your aesthetic.', '$34.95'),
('SWORD EARRING', '/images/sword-earring.webp', 'Earring', 'A homage to our generation’s obsession with video games, our Sword Earring is a nostalgic piece for us all. The almighty sword is the foundational symbol of strength, protection, and courage.\nWear this earring to display your strength and willingness to fight for what you believe in.', '$26.95' ),
('ASTROLOGY WALLET CHAIN', './images/astrology-wallet-chain.webp', 'Wallet Chain', 'The universe right by your side, eager to aid you in any situation you face. With our Astrology Wallet Chain, unlock the power to channel energy from the strongest celestial bodies: the sun, the moon, and the stars.\nWith its purposefully simple yet elegant design, it’s a nice way to add another touch of style to your fit without stealing the show. This wallet chain not only connects your wallet to your pants but also your entire outfit together by allowing you to rock an elevated style that’s still clean and structured.', '$99.95'),
('FLOODED GRILL RING', './images/flooded-grill-ring.webp', 'Ring', 'The beauty of life comes from knowing it’ll end. The horror of death is its permanence. Our Flooded Grill Ring embodies the natural cycle of life and the dichotomy between our emotional states.\nThere’s only one way to truly be free: realize that joy follows misery and vice versa - you can’t have one without the other. Featured in the NIGHTMARE Collection', '$36.95'),
('STAR RING', './images/star-ring.webp', 'Ring', 'Dazzle up your fit with a beacon of hope. Our simple yet stylish Star Ring adds a perfect finishing touch of elegance.', '$36.95'),
('GRILL RING', './images/grill-ring.webp', 'Ring', 'Grills are meant to be a loud form of self-expression. Our tasteful Grill Ring puts that meaning into a precise-fitting ring. Although designed to be uniquely attention-grabbing, the Grill Ring is a versatile accessory that’ll give almost any outfit that extra pop of style.\nFeatured in the NIGHTMARE Collection', '$32.95'),
('3MM STERLING SILVER FIGARO CHAIN', './images/3mm-sterling-silver-figaro-chain.webp', 'Chain', 'For those who appreciate tasteful elegance within jewelry. The 3mm Sterling Silver Figaro Chain features a timeless pattern that adds a stylish layer of dimensional design - a series of triple links joined by an elongated connecting link. This classic silhouette makes it very versatile, complimenting almost any other accessory and fitting nearly all HJ pendants.', '$36.95'),
('2.5MM STERLING SILVER ROPE CHAIN', './images/25mm-sterling-silver-rope-chain.webp', 'Chain', 'The 2.5mm Sterling Silver Rope Chain features a twisted design that resembles a braided rope. Adding texture and dimension, this gives it a “tight-knit” feeling, conveying expert craftsmanship alongside luxury and sophistication.', '$36.95'),
('DOWN YOUR THROAT PENDANT', './images/down-your-throat-pendant.webp', 'Pendant', 'A 100% HJ original, the Down Your Throat Pendant is our take on a deeply meaningful cross. It symbolizes how religion is often pushed down our throats - resulting in a negative experience within our generally positive spiritual world.\nWear this pendant as a stylish and meaningful statement piece that serves as a reminder that the beauty of life comes from the freedoms within it.\nFeatured in the Valentine’s Day 2022 Collection\nSave on your order when you add an HJ chain. Couple this pendant with your choice of a 20” chain, ensuring you get the best match for your aesthetic.', '$36.95');

insert into "sizes"
  ("itemId", "size")
  values
  (1, '7" (FITTED)'),
  (1, '8" (LOOSE FIT)'),
  (2, '3'),
  (2, '4'),
  (2, '5'),
  (2, '6'),
  (2, '7'),
  (2, '8'),
  (2, '9'),
  (2, '10'),
  (2, '11'),
  (2, '12'),
  (2, '13'),
  (3, '16"'),
  (3, '18"'),
  (3, '20"'),
  (3, '24"'),
  (4, 'REGULAR'),
  (5, 'SINGLE'),
  (5, 'PAIR'),
  (6, '22"'),
  (7, '3'),
  (7, '4'),
  (7, '5'),
  (7, '6'),
  (7, '7'),
  (7, '8'),
  (7, '9'),
  (7, '10'),
  (7, '11'),
  (7, '12'),
  (7, '13'),
  (8, '3'),
  (8, '4'),
  (8, '5'),
  (8, '6'),
  (8, '7'),
  (8, '8'),
  (8, '9'),
  (8, '10'),
  (8, '11'),
  (8, '12'),
  (8, '13'),
  (9, '3'),
  (9, '4'),
  (9, '5'),
  (9, '6'),
  (9, '7'),
  (9, '8'),
  (9, '9'),
  (9, '10'),
  (9, '11'),
  (9, '12'),
  (9, '13'),
  (10, '16"'),
  (10, '18"'),
  (10, '20"'),
  (10, '22"'),
  (11, '16"'),
  (11, '18"'),
  (11, '20"'),
  (11, '22"'),
  (12, 'REGULAR'),
  (12, 'XL');

insert into "materials"
  ("itemId", "material")
  values
  (1, 'SOLID STAINLESS STEEL' ),
  (2, 'SOLID STAINLESS STEEL'),
  (2, 'SOLID .925 STERLING SILVER' ),
  (3, 'SOLID STAINLESS STEEL'),
  (4, 'SOLID STAINLESS STEEL'),
  (5, 'SOLID STAINLESS STEEL'),
  (5, 'SOLID .925 STERLING SILVER'),
  (6, 'SOLID STAINLESS STEEL'),
  (7, 'SOLID STAINLESS STEEL'),
  (7, 'SOLID .925 STERLING SILVER'),
  (8, 'SOLID STAINLESS STEEL'),
  (9, 'SOLID STAINLESS STEEL'),
  (9, 'SOLID .925 STERLING SILVER'),
  (10, 'SOLID .925 STERLING SILVER'),
  (11, 'SOLID .925 STERLING SILVER'),
  (12, 'SOLID STAINLESS STEEL'),
  (12, 'SOLID .925 STERLING SILVER');

  insert into "listingImages"
  ("itemId", "imageURL")
  values
  (1, 'cuban-bracelet.webp'),
  (1, 'cuban-bracelet-2.webp'),
  (1, 'cuban-bracelet-3.webp'),
  (1, 'cuban-bracelet-4.webp'),
  (1, 'cuban-bracelet-5.webp'),
  (2, 'astrology-ring.webp'),
  (2, 'astrology-ring-2.webp'),
  (2, 'astrology-ring-3.webp'),
  (2, 'astrology-ring-4.webp'),
  (2, 'astrology-ring-5.webp'),
  (3, '10-mm-heavy-cuban-chain.webp'),
  (3, '10-mm-heavy-cuban-chain-2.webp'),
  (3, '10-mm-heavy-cuban-chain-3.webp'),
  (3, '10-mm-heavy-cuban-chain-4.webp'),
  (3, '10-mm-heavy-cuban-chain-5.webp'),
  (4, 'butterfly-pendant.webp'),
  (4, 'butterfly-pendant-2.webp'),
  (4, 'butterfly-pendant-3.webp'),
  (4, 'butterfly-pendant-4.webp'),
  (4, 'butterfly-pendant-5.webp'),
  (5, 'sword-earring.webp'),
  (5, 'sword-earring-2.webp'),
  (5, 'sword-earring-3.webp'),
  (5, 'sword-earring-4.webp'),
  (5, 'sword-earring-5.webp'),
  (6, 'astrology-wallet-chain.webp'),
  (6, 'astrology-wallet-chain-2.webp'),
  (6, 'astrology-wallet-chain-3.webp'),
  (6, 'astrology-wallet-chain-4.webp'),
  (6, 'astrology-wallet-chain-5.webp'),
  (7, 'flooded-grill-ring.webp'),
  (7, 'flooded-grill-ring-2.webp'),
  (7, 'flooded-grill-ring-3.webp'),
  (7, 'flooded-grill-ring-4.webp'),
  (7, 'flooded-grill-ring-5.webp'),
  (8, 'star-ring.webp'),
  (8, 'star-ring-2.webp'),
  (8, 'star-ring-3.webp'),
  (8, 'star-ring-4.webp'),
  (8, 'star-ring-5.webp'),
  (9, 'grill-ring.webp'),
  (9, 'grill-ring-2.webp'),
  (9, 'grill-ring-3.webp'),
  (9, 'grill-ring-4.webp'),
  (9, 'grill-ring-5.webp'),
  (10, '3mm-sterling-silver-figaro-chain.webp'),
  (10, '3mm-sterling-silver-figaro-chain-2.webp'),
  (10, '3mm-sterling-silver-figaro-chain-3.webp'),
  (10, '3mm-sterling-silver-figaro-chain-4.webp'),
  (10, '3mm-sterling-silver-figaro-chain-5.webp'),
  (11, '25mm-sterling-silver-rope-chain.webp'),
  (11, '25mm-sterling-silver-rope-chain-2.webp'),
  (11, '25mm-sterling-silver-rope-chain-3.webp'),
  (11, '25mm-sterling-silver-rope-chain-4.webp'),
  (11, '25mm-sterling-silver-rope-chain-5.webp'),
  (12, 'down-your-throat-pendant.webp'),
  (12, 'down-your-throat-pendant-2.webp'),
  (12, 'down-your-throat-pendant-3.webp'),
  (12, 'down-your-throat-pendant-4.webp'),
  (12, 'down-your-throat-pendant-5.webp');

insert into "inventory"
  ("itemId", "size", "material", "qtyInStock", "price")
  values
  (1, '7" (FITTED)', 'SOLID STAINLESS STEEL', 107, 3295),
  (1, '8" (LOOSE FIT)', 'SOLID STAINLESS STEEL', 108, 3295),
  (2, '3', 'SOLID STAINLESS STEEL', 81, 3695),
  (2, '4', 'SOLID STAINLESS STEEL', 82, 3695),
  (2, '5', 'SOLID STAINLESS STEEL', 83, 3695),
  (2, '6', 'SOLID STAINLESS STEEL', 84, 3695),
  (2, '7', 'SOLID STAINLESS STEEL', 85, 3695),
  (2, '8', 'SOLID STAINLESS STEEL', 77, 3695),
  (2, '9', 'SOLID STAINLESS STEEL', 89, 3695),
  (2, '10', 'SOLID STAINLESS STEEL', 810, 3695),
  (2, '11', 'SOLID STAINLESS STEEL', 110, 3695),
  (2, '12', 'SOLID STAINLESS STEEL', 120, 3695),
  (2, '13', 'SOLID STAINLESS STEEL', 130, 3695),
  (2, '3', 'SOLID .925 STERLING SILVER', 89, 9495),
  (2, '4', 'SOLID .925 STERLING SILVER', 88, 9495),
  (2, '5', 'SOLID .925 STERLING SILVER', 87, 9495),
  (2, '6', 'SOLID .925 STERLING SILVER', 86, 9495),
  (2, '7', 'SOLID .925 STERLING SILVER', 85, 9495),
  (2, '8', 'SOLID .925 STERLING SILVER', 84, 9495),
  (2, '9', 'SOLID .925 STERLING SILVER', 833, 9495),
  (2, '10', 'SOLID .925 STERLING SILVER', 81, 9495),
  (2, '11', 'SOLID .925 STERLING SILVER', 82, 9495),
  (2, '12', 'SOLID .925 STERLING SILVER', 84, 9495),
  (2, '13', 'SOLID .925 STERLING SILVER', 48, 9495),
  (3, '16"', 'SOLID STAINLESS STEEL', 14, 3695),
  (3, '18"', 'SOLID STAINLESS STEEL', 18, 3995),
  (3, '20"', 'SOLID STAINLESS STEEL', 22, 4295),
  (3, '24"', 'SOLID STAINLESS STEEL', 26, 4695),
  (4, 'REGULAR', 'SOLID STAINLESS STEEL', 8773, 3495),
  (5, 'SINGLE', 'SOLID STAINLESS STEEL', 11, 2695),
  (5, 'PAIR', 'SOLID STAINLESS STEEL', 22, 4695),
  (5, 'SINGLE', 'SOLID .925 STERLING SILVER', 0, 3695),
  (5, 'PAIR', 'SOLID .925 STERLING SILVER', 52, 6995),
  (6, '22"', 'SOLID STAINLESS STEEL', 457, 9995),
  (7, '3', 'SOLID STAINLESS STEEL', 81, 3695),
  (7, '4', 'SOLID STAINLESS STEEL', 82, 3695),
  (7, '5', 'SOLID STAINLESS STEEL', 83, 3695),
  (7, '6', 'SOLID STAINLESS STEEL', 84, 3695),
  (7, '7', 'SOLID STAINLESS STEEL', 85, 3695),
  (7, '8', 'SOLID STAINLESS STEEL', 77, 3695),
  (7, '9', 'SOLID STAINLESS STEEL', 89, 3695),
  (7, '10', 'SOLID STAINLESS STEEL', 810, 3695),
  (7, '11', 'SOLID STAINLESS STEEL', 110, 3695),
  (7, '12', 'SOLID STAINLESS STEEL', 120, 3695),
  (7, '13', 'SOLID STAINLESS STEEL', 130, 3695),
  (7, '3', 'SOLID .925 STERLING SILVER', 89, 8295),
  (7, '4', 'SOLID .925 STERLING SILVER', 88, 8295),
  (7, '5', 'SOLID .925 STERLING SILVER', 87, 8295),
  (7, '6', 'SOLID .925 STERLING SILVER', 86, 8295),
  (7, '7', 'SOLID .925 STERLING SILVER', 85, 8295),
  (7, '8', 'SOLID .925 STERLING SILVER', 84, 8295),
  (7, '9', 'SOLID .925 STERLING SILVER', 833, 8295),
  (7, '10', 'SOLID .925 STERLING SILVER', 81, 8295),
  (7, '11', 'SOLID .925 STERLING SILVER', 82, 8295),
  (7, '12', 'SOLID .925 STERLING SILVER', 84, 8295),
  (7, '13', 'SOLID .925 STERLING SILVER', 48, 8295),
  (8, '3', 'SOLID STAINLESS STEEL', 81, 3695),
  (8, '4', 'SOLID STAINLESS STEEL', 82, 3695),
  (8, '5', 'SOLID STAINLESS STEEL', 83, 3695),
  (8, '6', 'SOLID STAINLESS STEEL', 84, 3695),
  (8, '7', 'SOLID STAINLESS STEEL', 85, 3695),
  (8, '8', 'SOLID STAINLESS STEEL', 77, 3695),
  (8, '9', 'SOLID STAINLESS STEEL', 89, 3695),
  (8, '10', 'SOLID STAINLESS STEEL', 810, 3695),
  (8, '11', 'SOLID STAINLESS STEEL', 110, 3695),
  (8, '12', 'SOLID STAINLESS STEEL', 120, 3695),
  (8, '13', 'SOLID STAINLESS STEEL', 130, 3695),
  (9, '3', 'SOLID STAINLESS STEEL', 81, 3295),
  (9, '4', 'SOLID STAINLESS STEEL', 82, 3295),
  (9, '5', 'SOLID STAINLESS STEEL', 83, 3295),
  (9, '6', 'SOLID STAINLESS STEEL', 84, 3295),
  (9, '7', 'SOLID STAINLESS STEEL', 85, 3295),
  (9, '8', 'SOLID STAINLESS STEEL', 77, 3295),
  (9, '9', 'SOLID STAINLESS STEEL', 89, 3295),
  (9, '10', 'SOLID STAINLESS STEEL', 810, 3295),
  (9, '11', 'SOLID STAINLESS STEEL', 110, 3295),
  (9, '12', 'SOLID STAINLESS STEEL', 120, 3295),
  (9, '13', 'SOLID STAINLESS STEEL', 130, 3295),
  (9, '3', 'SOLID .925 STERLING SILVER', 89, 7295),
  (9, '4', 'SOLID .925 STERLING SILVER', 88, 7295),
  (9, '5', 'SOLID .925 STERLING SILVER', 87, 7295),
  (9, '6', 'SOLID .925 STERLING SILVER', 86, 7295),
  (9, '7', 'SOLID .925 STERLING SILVER', 85, 7295),
  (9, '8', 'SOLID .925 STERLING SILVER', 84, 7295),
  (9, '9', 'SOLID .925 STERLING SILVER', 833, 7295),
  (9, '10', 'SOLID .925 STERLING SILVER', 81, 7295),
  (9, '11', 'SOLID .925 STERLING SILVER', 82, 7295),
  (9, '12', 'SOLID .925 STERLING SILVER', 84, 7295),
  (9, '13', 'SOLID .925 STERLING SILVER', 48, 7295),
  (10, '16"', 'SOLID .925 STERLING SILVER', 101, 3695),
  (10, '18"', 'SOLID .925 STERLING SILVER', 101, 3995),
  (10, '20"', 'SOLID .925 STERLING SILVER', 101, 4295),
  (10, '22"', 'SOLID .925 STERLING SILVER', 101, 4695),
  (11, '16"', 'SOLID .925 STERLING SILVER', 121, 3695),
  (11, '18"', 'SOLID .925 STERLING SILVER', 131, 3995),
  (11, '20"', 'SOLID .925 STERLING SILVER', 141, 4295),
  (11, '22"', 'SOLID .925 STERLING SILVER', 151, 4695),
  (12, 'REGULAR', 'SOLID STAINLESS STEEL', 69, 3695),
  (12, 'XL', 'SOLID STAINLESS STEEL', 117, 25000),
  (12, 'REGULAR', 'SOLID .925 STERLING SILVER', 836, 9495),
  (12, 'XL', 'SOLID .925 STERLING SILVER', 17, 75000);

insert into "customers"
  ("username", "hashedPassword" )
  values
  ('test', 'testPass'),
  ('test2', 'testPass2');

insert into "cart"
  ("customerId", "itemId", "size", "material", "qty")
  values
  (1, 1, '7" (FITTED)', 'SOLID STAINLESS STEEL', 2),
  (1, 1, '8" (LOOSE FIT)', 'SOLID STAINLESS STEEL', 1),
  (2, 2, '3', 'SOLID STAINLESS STEEL', 1),
  (2, 2, '9', 'SOLID STAINLESS STEEL', 1);
